name: Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}

jobs:
  Pipeline:
    name: Default
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Reusing Workflows
      uses: actions/checkout@v3
      with:
        repository: punkerside/titan-bash
        ref: main
        path: .titan-bash/

    - name: Build
      uses: ./.titan-bash/pipelines/image/github
      with:
        DOCKERHUB_USER: ${DOCKERHUB_USER}
        DOCKERHUB_PASS: ${DOCKERHUB_PASS}