name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  Pipeline:
    name: Default
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Reusing Workflows
      uses: actions/checkout@v3
      with:
        repository: punkerside/titan-bash
        ref: main
        # token: ${{secrets.GITHUBSL_TOKEN}}
        path: .titan-bash/

    - name: Build
      uses: ./.titan-bash/pipelines/image/github